apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-html-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gmann-presidio/iu-kubesec.git
    targetRevision: HEAD
    path: argo-apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true