apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        configmap.reloader.stakater.com/reload: {{ .Values.name }}-configmap
        reloader.stakater.com/match: "true"
    spec:
      containers:
        - name: {{ .Values.webserver }}
          image: >-
            {{- if .Values.image.registry }}
            {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
            {{- else }}
            {{ .Values.image.repository }}:{{ .Values.image.tag }}
            {{- end }}
          {{- if not .Values.image.registry }}
          imagePullPolicy: Never
          {{- end }}
          {{- if eq .Values.webserver "apache" }}
          securityContext:
            runAsUser: 33
            runAsGroup: 33
          {{- end }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: {{ if eq .Values.webserver "apache" }}/usr/local/apache2/htdocs{{ else }}/usr/share/nginx/html{{ end }}
              readOnly: true

        - name: {{ .Values.scansidecar.name }}
          image: "{{ .Values.scansidecar.registry }}/{{ .Values.scansidecar.repository }}:{{ .Values.scansidecar.tag }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              freshclam && \
              while true; do
                echo "Scanning files..."
                clamscan -r /scan-volume
                sleep 60
              done
          volumeMounts:
            - name: html-volume
              mountPath: /scan-volume
              readOnly: true

      volumes:
        - name: html-volume
          configMap:
            name: {{ .Values.name }}-configmap