apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: green
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gmann-presidio/iu-kubesec.git
    targetRevision: feature/playwithstuff
    path: charts/gitops-html
    helm:
      valueFiles:
        - ../../apps/green/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: green
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true